<?php

/**
 *  
 */

function entity_sync_push_entities_info() {
  $items = array();
  $items['entity_sync_push'] = array(
    'label'                      => t('Entity Sync Push'),
    'plural label'               => "pushes",
    'base table'                 => "entity_sync_push",
    'revision table'             => "entity_sync_push_revision",
    'description'                => "A 'push' is a deployment's connection with a remote Drupal site.",
    'entity keys'                => array(
      'id'                       => 'pid',
      'label'                    => 'title',
      'status'                   => 'status',
      'revision'                 => 'vid',
    ),
    'translation' => array(
      'locale' => false,
    ),
    'access_callback'            => 'entity_sync_push_access',
    'fieldable'                  => TRUE,
    'entity class'               => 'Drupal\EntitySync\Push',
    'controller class'           => 'Drupal\EntitySync\PushController',
    "admin ui"                   => array(
      "controller class"         => 'Drupal\EntitySync\PushUIController',
      'menu wildcard'            => '%entity',
      'overview form uri'        => 'entity_sync/push/%entity'
    ),
    'bundles'                    => array(
      'entity_sync_push'    => array(
        'label'                  => t('Entity Sync Push')
      ),
    ),
  );
  
  return $items;
}



function entity_sync_push_access() {
  return true;
}

/**
 * Entity URI callback.
 */
function entity_sync_push_uri($entity) {
  return array(
    'path' => 'nebula_sync/push/' . $entity->pid,
  );
}