<?php

/**
 *  
 */

function entity_sync_deployment_entities_info() {
  $items = array();
  $path = drupal_get_path("module", "entity_sync_deployment");
  $items['entity_sync_deployment'] = array(
    'label'                      => t('Entity Sync Deployment'),
    'base table'                 => "entity_sync_deployment",
    'revision table'             => "entity_sync_deployment_revision",
    'description'                => "A 'deployment' is a group of entities that can be pulled from another Drupal Installation.",
    'entity keys'                => array(
      'id'                       => 'did',
      'label'                    => 'title',
      'status'                   => 'status',
      'revision'                 => 'vid',
    ),
    'translation' => array(
      'locale' => false,
    ),
    'access_callback'            => 'entity_sync_deployment_access',
    'fieldable'                  => TRUE,
    'entity class'               => 'EntitySyncDeployment',
    'controller class'           => 'EntitySyncDeploymentController',
    "admin ui"                   => array(
      "path"                     => "entity_sync/deployment",
      "controller class"         => 'EntitySyncDeploymentUIController',
      'menu wildcard'            => '%entity_sync_deployment',
      'overview form uri'        => 'entity_sync/deployments'
    ),
    'bundles'                    => array(
      'entity_sync_deployment'    => array(
        'label'                  => t('Entity Sync Deployment')
      ),
    ),
  );
  
  return $items;
}



