<?php


function entity_sync_yaml_menu() {
  $items = array();
  // entity_sync/<operation>/<enttiy_type>/<uuid>
  $items['entity_sync/yaml/view/%entity_sync_yaml_export/%'] = array(
    'title' => 'Entity YAML Operations',
    'page callback' => 'entity_sync_yaml',
    'page arguments' => array( 2, 3, 4),
    'access callback' => 'entity_sync_yaml_access',
    'access arguments' => array( 2, 3, 4),
    'load arguments' => array( 2, 3, 4),
    'description' => 'get entity as yaml.',
    'type' => MENU_CALLBACK
  );
  $items['entity_sync/yaml/update/%entity_sync_yaml_export/%'] = array(
    'title' => 'Entity YAML Operations',
    'page callback' => 'drupal_get_form',
    'page arguments' => array( "entity_sync_yaml_update", 2, 3, 4),
    'access callback' => 'entity_sync_yaml_access',
    'access arguments' => array( 2, 3, 4),
    'load arguments' => array( 2, 3, 4),
    'description' => 'get entity as yaml.',
    'type' => MENU_CALLBACK
  );
  return $items;
}

function entity_sync_forms() {
  return array(
    "entity_sync_yaml_update"
  );
}

function entity_sync_yaml_access($op, $entity_type, $uuid) {
  return true;
  //$entity = entity_sync_load_yaml_entity_by_uuid($uuid);
  //return entity_access($op, $entity_type, $entity);
}

function entity_sync_yaml_export_load($load_arg, $op, $entity_type, $uuid) {
  $args = func_get_args();
  $class = ucwords($entity_type);
  $classname = "Drupal\EntitySync\Export\\{$class}";
  xdebug_break();
  
  try {
    xdebug_break();
    $toReturn = @new $classname($uuid);
  } catch(Exception $e) {
    $toReturn = new \Drupal\EntitySync\Export\Entity($uuid);
    if (($toReturn instanceOf \Drupal\EntitySync\Export\Entity) && 
        ($toReturn->entityType == trim(arg(3)))) {
      return $toReturn;
    } else {
      xdebug_break();
      watchdog_exception("entity_sync_yaml", $e, "Having trouble instantiating the export class");
      return false;
    }
  }
  if ($toReturn instanceOf $classname) {
    return $toReturn;
  } else {
    return false;
  }
}


// example UUID: a3181cdc-6b5c-3854-6daa-b02b78218036

function entity_sync_yaml($op, $exporter, $uuid) {
  xdebug_break();  
  $exporter->applyOperation($op);
  exit();
}

function entity_sync_yaml_update($form, &$form_state, $op, $entity_type, $uuid) {
  
  xdebug_break();
  
  return $form;
}

function entity_sync_yaml_update_submit($form, &$form_state, $op, $entity_type, $uuid) {
  
  xdebug_break();
  
}